//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSYU.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HOSYU.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnString {
            get {
                return ResourceManager.GetString("ConnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon hosyu {
            get {
                object obj = ResourceManager.GetObject("hosyu", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   受付番号：|管轄：|部署：|受付日時：|システム名：|症状：|連絡日時：|報告：|入力担当：|完了日時：|担当：|原因：|処置：|出力データ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LblKeys {
            get {
                return ResourceManager.GetString("LblKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|60|61|62|63|64|65|66|67|68|69|70|71|72|73|74|75|76|77|78|79|80|81|82|83|84|85|86|87|88|89|90|91|92|93|94|95|96|97|98|99 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string resDomID {
            get {
                return ResourceManager.GetString("resDomID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT ACCEPTTABLE.ACCEPTID, POLICETABLE.AREADATA, POLICETABLE.POSTDATA, ACCEPTTABLE.ACCEPTDAYTIME, ACCEPTTABLE.SYSNAME, ACCEPTTABLE.SYMPTOM
        ///FROM ACCEPTTABLE LEFT JOIN POLICETABLE ON (ACCEPTTABLE.POSTID = POLICETABLE.POSTID) AND (ACCEPTTABLE.AREAID = POLICETABLE.AREAID); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlAccept {
            get {
                return ResourceManager.GetString("SqlAccept", resourceCulture);
            }
        }
    }
}
